// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: del_chirp_by_ID.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const deleteChirpByID = `-- name: DeleteChirpByID :exec
DELETE FROM chirps WHERE id = $1 AND user_id = $2
`

type DeleteChirpByIDParams struct {
	ID     uuid.UUID
	UserID uuid.UUID
}

func (q *Queries) DeleteChirpByID(ctx context.Context, arg DeleteChirpByIDParams) error {
	_, err := q.db.ExecContext(ctx, deleteChirpByID, arg.ID, arg.UserID)
	return err
}
